<?php

/**
 * @file
 * Install, update, and uninstall functions for the migrate_backdrop_ui module.
 */

use Drupal\Core\Url;

/**
 * Implements hook_install().
 */
function migrate_backdrop_ui_install() {
  $url = Url::fromRoute('migrate_backdrop_ui.upgrade')->toString();
  \Drupal::messenger()->addStatus(t('The Migrate Drupal UI module has been enabled. Proceed to the <a href=":url">upgrade form</a>.', [':url' => $url]));
}
